---
- name: Playbook to install geerlingguy.java on linux machine.
  hosts: all
  become: true

  tasks:
    # Install development tools
    - name: Install development tools.
      apt:
        name:
          - build-essential
          - wget
          - git
          - curl
          - ant
        state: present
        update_cache: true

    # Get date
    - name: Get date.
      command: date
      register: date_result

    - name: Display date.
      debug:
        var: date_result.stdout

    # Get hostname
    - name: Get hostname.
      shell: hostname
      register: hostname_result

    - name: Display hostname_result.
      debug:
        var: hostname_result.stdout

    # Get os-release
    - name: Get os-release.
      shell: "cat /etc/os-release"
      register: os_release_result

    - name: Display os_release_result.
      debug:
        var: os_release_result.stdout

    # Install CppUnit
    - name: Install CppUnit.
      apt:
        name:
          - libcppunit-dev
          - libcppunit-doc
          - xsltproc
        state: present

    # Install gtest
    - name: Install gtest.
      apt:
        name:
          - cmake
          - libgtest-dev
        state: present
        update_cache: true

    # Compile and install gtest
    - name: Compile and install gtest.
      shell: "cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make"

    # Include geerlingguy.java role
    - name: Include geerlingguy.java role.
      include_role:
        name: geerlingguy.java

    # Git checkout
    - name: Git checkout
      git:
        repo: "https://github.com/narethim/cpp_examples.git"
        dest: "/home/vagrant/checkout"
      become: false

    # Build using ant
    - name: Build using ant.
      shell: "cd /home/vagrant/checkout/ && ant"
      register: build_output

    - name: Display build_output.
      debug:
        var: build_output.stdout
