-- VectorCAST 20.sp1 (05/27/20)
-- Test Case Script
-- 
-- Environment    : ADDITION
-- Unit(s) Under Test: Addition
-- 
-- Script Features
TEST.SCRIPT_FEATURE:C_DIRECT_ARRAY_INDEXING
TEST.SCRIPT_FEATURE:CPP_CLASS_OBJECT_REVISION
TEST.SCRIPT_FEATURE:MULTIPLE_UUT_SUPPORT
TEST.SCRIPT_FEATURE:REMOVED_CL_PREFIX
TEST.SCRIPT_FEATURE:MIXED_CASE_NAMES
TEST.SCRIPT_FEATURE:STANDARD_SPACING_R2
TEST.SCRIPT_FEATURE:OVERLOADED_CONST_SUPPORT
TEST.SCRIPT_FEATURE:UNDERSCORE_NULLPTR
TEST.SCRIPT_FEATURE:FULL_PARAMETER_TYPES
TEST.SCRIPT_FEATURE:STRUCT_DTOR_ADDS_POINTER
TEST.SCRIPT_FEATURE:STRUCT_FIELD_CTOR_ADDS_POINTER
TEST.SCRIPT_FEATURE:STATIC_HEADER_FUNCS_IN_UUTS
TEST.SCRIPT_FEATURE:VCAST_MAIN_NOT_RENAMED
--

-- Unit: Addition

-- Subprogram: Addition::twoValues

-- Test Case: BASIS-PATH-001
TEST.UNIT:Addition
TEST.SUBPROGRAM:Addition::twoValues
TEST.NEW
TEST.NAME:BASIS-PATH-001
TEST.BASIS_PATH:1 of 1
TEST.NOTES:
   No branches in subprogram
TEST.END_NOTES:
TEST.VALUE:Addition.<<GLOBAL>>.(cl).Addition.Addition.<<constructor>>.Addition().<<call>>:0
TEST.VALUE:Addition.Addition::twoValues.x:<<MIN>>
TEST.VALUE:Addition.Addition::twoValues.y:<<MIN>>
TEST.END
